# Generated by Django 4.2.5 on 2023-10-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='link',
            field=models.URLField(),
        ),
    ]
