# Generated by Django 4.2.5 on 2023-10-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_alter_recurso_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='estrenos'),
        ),
    ]
