# Generated by Django 4.2.5 on 2023-10-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0011_recurso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='recursos'),
        ),
    ]
