# Generated by Django 4.2.5 on 2023-10-11 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_post_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fechaComentario']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='fechaComentario',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
