# Generated by Django 4.2.5 on 2023-10-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_alter_comentario_options_comentario_fechacomentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fechaComentario',
        ),
    ]
